server:
  port: 8080
spring:
  application:
    name: smart-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://smart-user

          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1