<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.smart.ai</groupId>
        <artifactId>smart-backend</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>smart-api</artifactId>
    <packaging>pom</packaging>
    <name>smart-api</name>
    <description>API 模块聚合父模块</description>

    <modules>
        <module>smart-api-user</module>
        <module>smart-api-auth</module>
        <module>smart-api-document</module>
        <module>smart-api-ai</module>
    </modules>

</project>