spring:
  application:
    name: smart-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_insight?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ip: 127.0.0.1

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

server:
  port: 8081
